language: java
jdk:
  - oraclejdk8
  
before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"
  - "cd VWorkflows-FX"

install:
    - TERM=dumb ./gradlew --refresh-dependencies --stacktrace

script:
    - TERM=dumb ./gradlew build --stacktrace

after_failure:
  - "cat ./build/test-results/*.xml"
  
after_success:
  - TERM=dumb ./gradlew test codeCoverageReport coveralls --stacktrace
